export const seo = {
	locale: "id",
	author: "Muhammad Yusuf",
	creator: "iamyuu027",
	title: "Jadwal Sholat",
	description:
		"⏰ Cek jadwal sholat berikutnya di kota Anda. Tanpa iklan, tanpa analitik, sepenuhnya gratis.",
	url: "",
	image: "og.png",
	imageAlt: "Aplikasi Jadwal Sholat",
	keywords: [
		"adzan",
		"waktu adzan",
		"waktu sholat",
		"jadwal sholat",
		"adzan terdekat",
		"adzan berikutnya",
		"adzan hari ini",
		"waktu adzan terdekat",
		"waktu adzan berikutnya",
		"waktu adzan hari ini",
		"waktu sholat terdekat",
		"waktu sholat berikutnya",
		"waktu sholat hari ini",
		"jadwal sholat terdekat",
		"jadwal sholat berikutnya",
		"jadwal sholat hari ini",
	].join(","),
};
